export const STUDENT_WORKFLOW_STATUS = Object.freeze({
  CHUA_DANG_KY_MANG: 'CHUA_DANG_KY_MANG',
  DA_DANG_KY_MANG: 'DA_DANG_KY_MANG',
  CHUA_CO_NHOM: 'CHUA_CO_NHOM',
  DA_CO_NHOM: 'DA_CO_NHOM',
  DA_CO_DE_TAI: 'DA_CO_DE_TAI',
});

export const GROUP_STATUS = Object.freeze({
  NHAP: 'NHAP',
  DANG_TUYEN_THANH_VIEN: 'DANG_TUYEN_THANH_VIEN',
  DA_DU_THANH_VIEN: 'DA_DU_THANH_VIEN',
  CHUA_CO_GIANG_VIEN: 'CHUA_CO_GIANG_VIEN',
  DA_CO_GIANG_VIEN: 'DA_CO_GIANG_VIEN',
  DANG_CHON_DE_TAI: 'DANG_CHON_DE_TAI',
  CHO_DUYET_DE_TAI: 'CHO_DUYET_DE_TAI',
  CAN_CHINH_SUA_DE_TAI: 'CAN_CHINH_SUA_DE_TAI',
  DA_DUYET_DE_TAI: 'DA_DUYET_DE_TAI',
  DA_CHOT_DE_TAI: 'DA_CHOT_DE_TAI',
});

export const TOPIC_SUBMISSION_STATUS = Object.freeze({
  NHAP: 'NHAP',
  CHO_GIANG_VIEN_DUYET: 'CHO_GIANG_VIEN_DUYET',
  CAN_CHINH_SUA: 'CAN_CHINH_SUA',
  DA_DUYET: 'DA_DUYET',
  TU_CHOI: 'TU_CHOI',
  DA_CHOT: 'DA_CHOT',
});

export const INVITATION_STATUS = Object.freeze({
  CHO_XAC_NHAN: 'CHO_XAC_NHAN',
  DA_CHAP_NHAN: 'DA_CHAP_NHAN',
  DA_TU_CHOI: 'DA_TU_CHOI',
  DA_HUY: 'DA_HUY',
});
